name: "Build in Public Export"
on:
  push:
    branches: [ 'main' ]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eddspire/action.buildinpublic.so@v1
        with:
          api-token: ${{ secrets.BUILDINPUBLIC_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
